### ISSUE TITLE
enum形式の検証について

### ISSUE THREAD

**Issue by niyariver** [ototadana/fixture-book#12]
こちら本日会話させて頂いた件について、起票させて頂きます。

要望内容：
テスト対象メソッドの戻り値がenum形式の場合、E.取得データに指定が出来ないため、
可能であればエンハンスをお願いしたく思っております。

お手数おかけしてすみませんが、ご確認の程宜しくお願い致します。

**Comment by ototadana** [comment]
E.取得データ の列名行に `-` を指定すれば、enum および通常のオブジェクトに関しても「toString() メソッドの戻り値と比較する」という動きに変更しようと思います。
(現状 int 等の基本型と String に関しては、'-' 指定での比較が可能なのですが、それをすべてのオブジェクトに適用できるようします）

こうすれば、 `enum TestEnum {ONE, TWO}`  の `TestEnum.ONE` が Excell 上の "ONE" 比較検証できるようになるはず。

**Comment by ototadana** [comment]
[バージョン5.6](http://search.maven.org/#artifactdetails%7Ccom.xpfriend%7Cfixture-book%7C5.6%7Cjar)で対応しました。

**Comment by niyariver** [comment]
ご対応ありがとうございます。
頂いた件確認させて頂きます。
